### ISSUE TITLE
Basic page template layout/styles

### ISSUE THREAD

**Issue by mandiwise** [redacademy/big-sisters-winter-2016#3]
Make sure that the `page.php` template has been appropriately styled so it can be used by the internal end users at Big Sisters should they need to create pages on a one-off basis (as an example, this page obviously doesn't look quite complete: http://bigsisters.alanchow.ca/events/).

Remove the call to `get_sidebar()` if you don't need it.

**Comment by jemalmazar** [comment]
Added basic styles and removed get_sidebar().
