### ISSUE TITLE
Responsive CSS details

### ISSUE THREAD

**Issue by mandiwise** [redacademy/big-sisters-winter-2016#6]
Be sure to test all of your layouts to make sure that the design works fluidly, e.g.:

<img width="174" alt="button-menu-overlap" src="https://cloud.githubusercontent.com/assets/1518780/14194084/4bf0373a-f75f-11e5-9461-927413c14444.png">

<img width="917" alt="text-wrapping" src="https://cloud.githubusercontent.com/assets/1518780/14194086/4e7a97e8-f75f-11e5-9e50-22562b68c5ae.png">

**Comment by wngtn-dles** [comment]
Jeremiah fixed the navigation issue and I just fixed the css issue on front page hero stories.
